#当前项目名称
spring:
  application:
    name: order
#数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/imooc?characterEncoding=utf-8&useSSL=false
#开启jps 的 sql
  jpa:
    show-sql: true
# #注册eureka 服务
# eureka:
#   client:
#     service-url:
#       defaultZone: http://localhost:8762/eureka/
#当前项目端口
server:
  port: 8082
env:
  test
